
distributions:
  ribosomal: [447, 870, 406, 869, 405, 866, 1548, 404]
  rna_binding:
    GO RNA-binding: true
    ribosomal protein: false


species: "sp"
genus: "Synnechocystis"
tax_id: 11117

minGSSize: 30
maxGSSize: 500