
distributions:
  ribosomal: [447, 870, 406, 869, 405, 866, 1548, 404]
  rna_binding:
    GO RNA-binding: true
    ribosomal protein: false

benchmark_repeats:  10

font_size: 10
width: 624
height: 400


species: "sp"
genus: "Synnechocystis"
tax_id: 11117

minGSSize: 30
maxGSSize: 500

nr_proteins: 200
multipanel_font_size: 14