
intensities: "Data/synIntensitiesIBAQ.tsv"
design: "Data/synDesignIBAQ.tsv"

bubble_plot:
  locus_tag: ["ssr3189","ssl2245", "slr0782", "sll0947", "slr0711", "slr0147", "sll0726", "slr0355", "slr2130", "ssl3335", "sll1967" ,"slr1531","sll0517" ,"slr1265" ,"sll7087", "slr1030", "sll1961", "slr0670", "sll1371", "sll1315"]

benchmark_repeats:  5
fonts:
  default:
    family: "Arial"
    size: 9.33
  legend:
    family: "Arial"
    size: 8
    color: "black"
  axis:
    family: "Arial"
    size: 8
  axis_ticks:
    family: "Arial"
    size: 8
  annotations:
    family: "Arial"
    size: 9.33
width: 680
height: 400

margin:
  b: 50
  t: 20
  r: 30
  l: 70

F3:
  A:
    height: 200
  B:
    height: 200
  C:
    height: 130

FR1:
  AB:
    height: 300
  C:
    height: 300

QCPlot:
  A:
    height: 300
  B:
    height: 300
  C:
    height: 400

HeLaPlot:
  A:
    height: 550
  B:
    height: 250

distributions:
  D1:
    locus_tags: ["ssr3189","ssl2245", "slr0782", "sll0947", "slr0711", "slr0147", "sll0726", "slr0355", "slr2130", "ssl3355", "sll1967" ,"slr1531","sll0517" ,"slr1265" ,"sll7087", "slr1030", "sll1961", "slr0670", "sll1371", "sll1315"]
    height: 793
    vertical_spacing: 0.022
    legend2_y: 1.05
  D2:
    locus_tags: ["sll1967" ,"slr1531","sll0517" ,"slr1265" ,"sll7087"]
    height: 500
    vertical_spacing: 0.05
    legend2_y: 1.1
  D3:
    locus_tags: [ "slr1356" ,"slr1984" ]
    height: 300
    vertical_spacing: 0.1
    legend2_y: 1.15
  S3:
    locus_tags: [ "ssl3437"]
    height: 300
    vertical_spacing: 0.1
    legend2_y: 1.15


natureMouseFig:
  A:
    height: 300
  B:
    ids: ["Stat5b", "Fgfr4"]
    height: 500
    vertical_spacing: 0.022
    legend2_y: 1.1


species: "sp"
genus: "Synnechocystis"
tax_id: 11117

minGSSize: 30
maxGSSize: 500

anosimCutoff: 0.48
multipanel_font_size: 7

Mouse:
  muscle:
    link: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-021-27398-y/MediaObjects/41467_2021_27398_MOESM16_ESM.xlsx"
    data_sheet: "S13B-log2 proc MouseMuscle PROT"
    col_sheet: "S13A-Output SN MouseMuscle PROT"
  egf_kidney:
    link: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-021-27398-y/MediaObjects/41467_2021_27398_MOESM11_ESM.xlsx"
    data_sheet: "S8B-log2 processed data Kidney"
    col_sheet: "S8A-Output SN Kidney"
  egf_liver:
    link: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-021-27398-y/MediaObjects/41467_2021_27398_MOESM12_ESM.xlsx"
    data_sheet: "S9B-log2 processed Liver"
    col_sheet: "S9A-Output Spectronaut Liver"

  egf_8min:
    link: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-021-27398-y/MediaObjects/41467_2021_27398_MOESM8_ESM.xlsx"
    data_sheet: "S5B-Log2 proc HeLa+EGF PROT"
    col_sheet: "S5A-Output SN Hela+EGF PROT"
  egf_2min:
    link: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-021-27398-y/MediaObjects/41467_2021_27398_MOESM8_ESM.xlsx"
    data_sheet: "S5B-Log2 proc HeLa+EGF PROT"
    col_sheet: "S5A-Output SN Hela+EGF PROT"
  egf_20min:
    link: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-021-27398-y/MediaObjects/41467_2021_27398_MOESM8_ESM.xlsx"
    data_sheet: "S5B-Log2 proc HeLa+EGF PROT"
    col_sheet: "S5A-Output SN Hela+EGF PROT"
  egf_90min:
    link: "https://static-content.springer.com/esm/art%3A10.1038%2Fs41467-021-27398-y/MediaObjects/41467_2021_27398_MOESM8_ESM.xlsx"
    data_sheet: "S5B-Log2 proc HeLa+EGF PROT"
    col_sheet: "S5A-Output SN Hela+EGF PROT"