
intensities: "Data/synIntensitiesIBAQ.tsv"
design: "Data/synDesignIBAQ.tsv"

distributions:
  rplA: [447]
  rna_binding:
    GO RNA-binding: true
    ribosomal protein: false

benchmark_repeats:  1
fonts:
  default:
    family: "Arial"
    size: 12
  legend:
    family: "Arial"
    size: 10
    color: "black"
  axis:
    family: "Arial"
    size: 12
  axis_ticks:
    family: "Arial"
    size: 10
  annotations:
    family: "Arial"
    size: 12
width: 624
height: 400

margin:
  b: 15
  t: 20
  r: 30
  l: 30

F3:
  A:
    height: 300
  B:
    height: 130
  C:
    height: 400



species: "sp"
genus: "Synnechocystis"
tax_id: 11117

minGSSize: 30
maxGSSize: 500

nr_proteins: 200
multipanel_font_size: 14