name: synRDPMSpec
channels:
 - conda-forge
 - bioconda
dependencies:
 - snakemake=8.14
 - pandas=2.2.0
 - pip
 - python=3.11
 - openpyxl
 - svgutils
 - pillow
 - matplotlib-venn
 - matplotlib
 - requests
 - rpy2
 - r-base
 - bioconductor-dapar
 - bioconductor-msnbase
 - pip:
    - rapdor==0.1.9
    - kaleido==0.2.1
